### ISSUE TITLE
Add Localization

### ISSUE THREAD

**Issue by FrenchTacoDev** [FrenchTacoDev/ultra_light_performance_tool#2]
Implement internationalization and localization as described by the following best practices:

[Flutter Documentation](https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization)

**Comment by FrenchTacoDev** [comment]
When publishing and mergin into 0.3.0, A change in the readme on how to use ULPT is necessary.

- Add a file called l10n.yaml to your apps base directory
- Add the following code to it

```yaml
arb-dir: ../lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
```

- In pubspec.yaml under flutter add: 

```yaml
flutter:
  generate:true
```
